version: "3.8"

services:
  my-node-app:
    build:
      context: .
      target: production
    volumes:
      - './:/app'
      - '/app/node_modules'  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=production
    # ports:
    #   - "4000:4000"
    command: ["npm", "start"]
    restart: always
