
services:
  my-node-app:
    container_name: my-node-prod
    build:
      context: .
      target: production

    volumes:
      - './:/app'  # Sync entire project with container
      - '/app/node_modules'  # Prevent overwriting node_modules in container

    environment:
      - NODE_ENV=production  

    ports:
      - "4000:4000"

    command: ["npm", "start"]  # Start the Node.js app

    restart: always
